[workspace]
members = ["app"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["{{authors}}"]
license = "MIT"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
