name: 'postgres'

services:
  db:
    image: postgres:17.2-bookworm
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: always
    volumes:
      - type: volume
        source: dating-db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    ports:
      - "5432:5432"
  ui:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - pgadmin-data1:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
  redis:
    image: redis/redis-stack:7.4.0-v2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - type: volume
        source: redis-data1
        target: /data
volumes:
  dating-db-data:
  pgadmin-data1:
  redis-data1:
